version: "3.8"

services:
  devcontainer:
    build: .
    container_name: devcontainer
    image: vscode_devcontainer
    command: sleep infinity
    privileged: true
    init: true

    volumes:
      - ../..:/workspaces:cached
      - dind-var-lib-docker:/var/lib/docker

    networks:
      workspaces:

volumes:
  dind-var-lib-docker:

networks:
  workspaces:
    name: vscode
    driver: bridge
