version: "3.8"
name: twingate

services:
  twingate_connector:
    container_name: twingate_connector
    image: twingate/connector
    restart: unless-stopped

    sysctls:
      net.ipv4.ping_group_range: "0 2147483647"

    environment:
      - TWINGATE_NETWORK=$TWINGATE_NETWORK
      - TWINGATE_ACCESS_TOKEN=$TWINGATE_ACCESS_TOKEN
      - TWINGATE_REFRESH_TOKEN=$TWINGATE_REFRESH_TOKEN
      # - TWINGATE_LOG_LEVEL=$TWINGATE_LOG_LEVEL # (Optional) Change loglevel
      # - TWINGATE_DNS=$TWINGATE_DNS # (Optional) Add custom DNS Server

    networks:
      custom:

volumes:
  data:
  config:

networks:
  custom:
    name: ztn
    driver: bridge
    # external: true # (Optional) When attaching an external network
