api:
  dashboard: true
  insecure: true

entryPoints:
  http:
    address: :80

    # http:
    #   redirections:
    #     entrypoint:
    #       to: https
    #       scheme: https

  https:
    address: :443

# certificatesResolvers:
#   production:
#     acme:
#       email: example@email.com
#       storage: /etc/traefik/certs/acme.json
#       caServer: "https://acme-v02.api.letsencrypt.org/directory"

#       keyType: EC256
#       dnsChallenge:
#         provider: cloudflare
#         resolvers:
#           - "1.1.1.1:53"
#           - "8.8.8.8:53"
#   staging:
#     acme:
#       email: example@email.com
#       storage: /etc/traefik/certs/acme.json
#       caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"

#       httpChallenge:
#         entryPoint: http

serversTransport:
  insecureSkipVerify: true

providers:
  docker:
    exposedByDefault: false
  file:
    filename: /etc/provider/config.yaml

global:
  checkNewVersion: false
  sendAnonymousUsage: false

# -- (Optional) Change Log Level and Format here...
# - loglevels [DEBUG, INFO, WARNING, ERROR, CRITICAL]
# - format [common, json, logfmt]
log:
  level: INFO
  format: json
  filePath: /var/log/traefik/traefik.log

accessLog:
  format: json
  filePath: /var/log/traefik/access.log
