services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped

    volumes:
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data

    ports:
      - $HTTP_PORT:$HTTP_PORT
      - $HTTPS_PORT:$HTTPS_PORT
    networks:
      proxy:

    labels:
      - "traefik.enable=true"
      - "traefik.http.services.portainer.loadbalancer.server.port=$PORTAINER_PORT"
      - "traefik.http.routers.portainer.rule=Host(`portainer.${DOMAIN}`)"

volumes:
  data:
